# Generated by Django 4.2.7 on 2023-11-15 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AFM', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenses',
            name='Date_Expenses',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='incomes',
            name='ChekDate_Incomes',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jobhistory',
            name='Date_JobHistory',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='FinishDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='StartDate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
