# Generated by Django 4.2.7 on 2023-11-15 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AFM', '0003_alter_expenses_companyname_paying_expenses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenses',
            name='CompanyName_Paying_Expenses',
            field=models.CharField(blank=True, default='Genel Gider', max_length=63, null=True),
        ),
    ]
