# Generated by Django 4.2.7 on 2023-11-15 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AFM', '0004_alter_expenses_companyname_paying_expenses'),
    ]

    operations = [
        migrations.CreateModel(
            name='Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Detail', models.CharField(max_length=63)),
            ],
        ),
    ]
