# Generated by Django 4.2.7 on 2023-11-25 10:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("AFM", "0006_alter_expenses_amount_expenses_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="expenses",
            name="ProjectName_Expenses",
            field=models.CharField(max_length=63),
        ),
    ]
