# Generated by Django 4.2.7 on 2023-11-25 13:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("AFM", "0007_alter_expenses_projectname_expenses"),
    ]

    operations = [
        migrations.AddField(
            model_name="expenses",
            name="ProjectName_Expenses_Copy",
            field=models.CharField(blank=True, max_length=63, null=True),
        ),
    ]
