# Generated by Django 4.2.7 on 2023-11-28 13:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("AFM", "0010_incomes_projectname_incomes_copy_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="clients",
            name="CompanyName_Clients_New",
            field=models.CharField(blank=True, max_length=63, null=True),
        ),
    ]
