# Generated by Django 4.2.7 on 2023-11-28 15:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("AFM", "0011_clients_companyname_clients_new"),
    ]

    operations = [
        migrations.AddField(
            model_name="supplier",
            name="CompanyName_Supplier_New",
            field=models.CharField(blank=True, max_length=63, null=True),
        ),
    ]
