# Generated by Django 4.2.7 on 2023-11-28 15:48

import AFM.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("AFM", "0012_supplier_companyname_supplier_new"),
    ]

    operations = [
        migrations.AlterField(
            model_name="supplier",
            name="CompanyName_Supplier",
            field=models.CharField(
                blank=True,
                max_length=63,
                null=True,
                validators=[AFM.models.unique_supplier_validator],
            ),
        ),
    ]
