# Generated by Django 4.2.7 on 2023-11-28 16:02

import AFM.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("AFM", "0013_alter_supplier_companyname_supplier"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clients",
            name="CompanyName_Clients",
            field=models.CharField(
                blank=True,
                max_length=63,
                null=True,
                validators=[AFM.models.unique_supplier_validator],
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="ProjectName",
            field=models.CharField(
                blank=True,
                max_length=63,
                null=True,
                validators=[AFM.models.unique_supplier_validator],
            ),
        ),
    ]
