# Generated by Django 4.2.7 on 2023-11-28 20:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("AFM", "0014_alter_clients_companyname_clients_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="AC_Power",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name="project",
            name="Cost_NotIncludingKDV",
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name="project",
            name="DC_Power",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
