# Generated by Django 4.2.7 on 2023-11-30 18:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("AFM", "0018_alter_expenses_amount_expenses_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="incomes",
            name="CompanyName_Pay_Incomes",
            field=models.CharField(blank=True, max_length=63, null=True),
        ),
    ]
