# Generated by Django 4.2.7 on 2023-12-02 12:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("AFM", "0019_incomes_companyname_pay_incomes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clients",
            name="CompanyName_Clients",
            field=models.CharField(blank=True, max_length=63, null=True),
        ),
        migrations.AlterField(
            model_name="project",
            name="ProjectName",
            field=models.CharField(blank=True, max_length=63, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="supplier",
            name="CompanyName_Supplier",
            field=models.CharField(blank=True, max_length=63, null=True),
        ),
    ]
