# Generated by Django 4.2.7 on 2023-12-03 02:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("AFM", "0020_alter_clients_companyname_clients_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clients",
            name="CompanyName_Clients",
            field=models.CharField(blank=True, max_length=63, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="supplier",
            name="CompanyName_Supplier",
            field=models.CharField(blank=True, max_length=63, null=True, unique=True),
        ),
    ]
