# Generated by Django 4.2.7 on 2023-12-03 11:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("AFM", "0021_alter_clients_companyname_clients_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="KDV_Rate",
            field=models.CharField(blank=True, default="20", max_length=12, null=True),
        ),
    ]
