# Generated by Django 5.0 on 2023-12-13 20:21

import AFM.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("AFM", "0022_alter_project_kdv_rate"),
    ]

    operations = [
        migrations.CreateModel(
            name="SalesOfferCard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "Offer_Subject_Card",
                    models.CharField(blank=True, max_length=63, null=True),
                ),
                (
                    "Location_Card",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "Cost_NotIncludingKDV_Card",
                    AFM.models.TwoDecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "AC_Power_Card",
                    models.IntegerField(blank=True, default=0, null=True),
                ),
                (
                    "DC_Power_Card",
                    models.IntegerField(blank=True, default=0, null=True),
                ),
                (
                    "UnitCost_NotIncludingKDV",
                    AFM.models.TwoDecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("Situation_Card", models.CharField(default="Teklif", max_length=63)),
                ("Date_Card", models.DateField(blank=True, null=True)),
                (
                    "Terrain_Roof_Card",
                    models.CharField(blank=True, max_length=63, null=True),
                ),
                ("Offer_File_Card", models.FileField(upload_to="offer_files/")),
                ("M_File_Card", models.FileField(upload_to="m_files/")),
                (
                    "Client_Card",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="AFM.clients"
                    ),
                ),
            ],
        ),
    ]
