# Generated by Django 5.0 on 2023-12-14 20:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("AFM", "0023_salesoffercard"),
    ]

    operations = [
        migrations.AddField(
            model_name="salesoffercard",
            name="Comment_Date_Card",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="salesoffercard",
            name="Offer_Comment_Card",
            field=models.CharField(blank=True, max_length=63, null=True),
        ),
        migrations.AlterField(
            model_name="salesoffercard",
            name="Situation_Card",
            field=models.CharField(default="Potansiyel Müşteri", max_length=63),
        ),
    ]
