# Generated by Django 5.0 on 2023-12-14 20:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("AFM", "0024_salesoffercard_comment_date_card_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="salesoffercard",
            name="M_File_Card",
            field=models.FileField(blank=True, null=True, upload_to="m_files/"),
        ),
        migrations.AlterField(
            model_name="salesoffercard",
            name="Offer_File_Card",
            field=models.FileField(blank=True, null=True, upload_to="offer_files/"),
        ),
    ]
