# Generated by Django 5.0 on 2023-12-15 17:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("AFM", "0025_alter_salesoffercard_m_file_card_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="salesoffercard",
            name="Situation_Card",
            field=models.CharField(
                choices=[
                    ("Potansiyel Müşteri", "Potansiyel Müşteri"),
                    ("Maliyet Hesaplama", "Maliyet Hesaplama"),
                    ("Fiyat Belirleme", "Fiyat Belirleme"),
                    ("Teklif Hazırlama", "Teklif Hazırlama"),
                    ("Sunum Sonrası Görüşme", "Sunum Sonrası Görüşme"),
                    ("Teklif Sunuldu", "Teklif Sunuldu"),
                ],
                default="Potansiyel Müşteri",
                max_length=63,
            ),
        ),
    ]
