# Generated by Django 5.0 on 2023-12-21 21:19

import AFM.models
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("AFM", "0028_alter_salesoffercard_cost_notincludingkdv_card"),
    ]

    operations = [
        migrations.AlterField(
            model_name="salesoffercard",
            name="UnitCost_NotIncludingKDV",
            field=AFM.models.TwoDecimalField(
                blank=True, decimal_places=2, default=0, max_digits=12, null=True
            ),
        ),
    ]
