# Generated by Django 5.0 on 2023-12-21 21:21

import AFM.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("AFM", "0029_alter_salesoffercard_unitcost_notincludingkdv"),
    ]

    operations = [
        migrations.AlterField(
            model_name="salesoffercard",
            name="AC_Power_Card",
            field=models.IntegerField(blank=True, default="0", null=True),
        ),
        migrations.AlterField(
            model_name="salesoffercard",
            name="Cost_NotIncludingKDV_Card",
            field=AFM.models.TwoDecimalField(
                blank=True, decimal_places=2, default="0", max_digits=12, null=True
            ),
        ),
        migrations.AlterField(
            model_name="salesoffercard",
            name="DC_Power_Card",
            field=models.IntegerField(blank=True, default="0", null=True),
        ),
        migrations.AlterField(
            model_name="salesoffercard",
            name="UnitCost_NotIncludingKDV",
            field=AFM.models.TwoDecimalField(
                blank=True, decimal_places=2, default="0", max_digits=12, null=True
            ),
        ),
    ]
