# Generated by Django 5.0 on 2023-12-25 11:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("AFM", "0031_salesoffercard_is_lost"),
    ]

    operations = [
        migrations.AddField(
            model_name="salesoffercard",
            name="Client_Card_Copy",
            field=models.CharField(blank=True, max_length=63, null=True),
        ),
        migrations.AlterField(
            model_name="salesoffercard",
            name="Client_Card",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="AFM.clients",
            ),
        ),
    ]
