# Generated by Django 5.0 on 2023-12-25 13:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("AFM", "0032_salesoffercard_client_card_copy_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="salesoffercard",
            name="M_File_Card",
            field=models.FileField(
                blank=True, null=True, upload_to="AFM_files/m_files/"
            ),
        ),
        migrations.AlterField(
            model_name="salesoffercard",
            name="Offer_File_Card",
            field=models.FileField(
                blank=True, null=True, upload_to="AFM_files/offer_files/"
            ),
        ),
    ]
