# Generated by Django 5.0 on 2023-12-30 14:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("AFM", "0033_alter_salesoffercard_m_file_card_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="salesoffercard",
            name="M_File_Card",
            field=models.FileField(default="", upload_to="m_files"),
        ),
        migrations.AlterField(
            model_name="salesoffercard",
            name="Offer_File_Card",
            field=models.FileField(default="", upload_to="offer_files"),
        ),
    ]
