# Generated by Django 5.0 on 2023-12-30 14:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("AFM", "0034_alter_salesoffercard_m_file_card_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="salesoffercard",
            name="M_File_Card_2",
            field=models.FileField(default="", upload_to="m_files"),
        ),
        migrations.AddField(
            model_name="salesoffercard",
            name="M_File_Card_3",
            field=models.FileField(default="", upload_to="m_files"),
        ),
        migrations.AddField(
            model_name="salesoffercard",
            name="Offer_File_Card_2",
            field=models.FileField(default="", upload_to="offer_files"),
        ),
        migrations.AddField(
            model_name="salesoffercard",
            name="Offer_File_Card_3",
            field=models.FileField(default="", upload_to="offer_files"),
        ),
        migrations.AddField(
            model_name="salesoffercard",
            name="Offer_File_Card_4",
            field=models.FileField(default="", upload_to="offer_files"),
        ),
        migrations.AddField(
            model_name="salesoffercard",
            name="Offer_File_Card_5",
            field=models.FileField(default="", upload_to="offer_files"),
        ),
    ]
