# Generated by Django 5.0 on 2024-01-17 22:09

import AFM.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("AFM", "0036_alter_salesoffercard_m_file_card_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="salesoffercard",
            name="Is_Gain",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name="salesoffercard",
            name="Offer_Cost_NotIncludingKDV_Card",
            field=AFM.models.TwoDecimalField(
                blank=True, decimal_places=2, default="0", max_digits=12, null=True
            ),
        ),
        migrations.AddField(
            model_name="salesoffercard",
            name="Roof_Cost_Card",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="salesoffercard",
            name="UnitOffer_NotIncludingKDV",
            field=AFM.models.TwoDecimalField(
                blank=True, decimal_places=2, default="0", max_digits=12, null=True
            ),
        ),
    ]
