# Generated by Django 5.0 on 2024-01-20 14:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("AFM", "0037_salesoffercard_is_gain_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="salesoffercard",
            name="Is_late",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
