# Generated by Django 5.0 on 2024-01-20 17:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("AFM", "0038_salesoffercard_is_late"),
    ]

    operations = [
        migrations.AlterField(
            model_name="salesoffercard",
            name="Situation_Card",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Potansiyel Müşteri", "Potansiyel Müşteri"),
                    ("Maliyet Hesaplama", "Maliyet Hesaplama"),
                    ("Fiyat Belirleme", "Fiyat Belirleme"),
                    ("Teklif Hazırlama", "Teklif Hazırlama"),
                    ("Teklif Hazır", "Teklif Hazır"),
                    ("Teklif Sunuldu", "Teklif Sunuldu"),
                    ("Sunum Sonrası Görüşme", "Sunum Sonrası Görüşme"),
                ],
                default="Potansiyel Müşteri",
                max_length=63,
                null=True,
            ),
        ),
    ]
