# Generated by Django 5.0 on 2024-01-20 21:32

import AFM.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("AFM", "0039_alter_salesoffercard_situation_card"),
    ]

    operations = [
        migrations.CreateModel(
            name="SalesOfferCard_Revise",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "Client_Card_Copy",
                    models.CharField(blank=True, max_length=63, null=True),
                ),
                (
                    "Offer_Subject_Card",
                    models.CharField(blank=True, max_length=63, null=True),
                ),
                (
                    "Location_Card",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "Cost_NotIncludingKDV_Card",
                    AFM.models.TwoDecimalField(
                        blank=True,
                        decimal_places=2,
                        default="0",
                        max_digits=12,
                        null=True,
                    ),
                ),
                (
                    "Offer_Cost_NotIncludingKDV_Card",
                    AFM.models.TwoDecimalField(
                        blank=True,
                        decimal_places=2,
                        default="0",
                        max_digits=12,
                        null=True,
                    ),
                ),
                (
                    "AC_Power_Card",
                    models.IntegerField(blank=True, default="0", null=True),
                ),
                (
                    "DC_Power_Card",
                    models.IntegerField(blank=True, default="0", null=True),
                ),
                (
                    "UnitCost_NotIncludingKDV",
                    AFM.models.TwoDecimalField(
                        blank=True,
                        decimal_places=2,
                        default="0",
                        max_digits=12,
                        null=True,
                    ),
                ),
                (
                    "UnitOffer_NotIncludingKDV",
                    AFM.models.TwoDecimalField(
                        blank=True,
                        decimal_places=2,
                        default="0",
                        max_digits=12,
                        null=True,
                    ),
                ),
                (
                    "Situation_Card",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Potansiyel Müşteri", "Potansiyel Müşteri"),
                            ("Maliyet Hesaplama", "Maliyet Hesaplama"),
                            ("Fiyat Belirleme", "Fiyat Belirleme"),
                            ("Teklif Hazırlama", "Teklif Hazırlama"),
                            ("Teklif Hazır", "Teklif Hazır"),
                            ("Teklif Sunuldu", "Teklif Sunuldu"),
                            ("Sunum Sonrası Görüşme", "Sunum Sonrası Görüşme"),
                        ],
                        default="Potansiyel Müşteri",
                        max_length=63,
                        null=True,
                    ),
                ),
                ("Date_Card", models.DateField(blank=True, null=True)),
                (
                    "Terrain_Roof_Card",
                    models.CharField(
                        blank=True,
                        choices=[("Çatı", "Çatı"), ("Arazi", "Arazi")],
                        max_length=63,
                        null=True,
                    ),
                ),
                ("Roof_Cost_Card", models.IntegerField(blank=True, null=True)),
                ("Comment_Date_Card", models.DateField(blank=True, null=True)),
                (
                    "Offer_Comment_Card",
                    models.CharField(blank=True, max_length=63, null=True),
                ),
                (
                    "Offer_File_Card",
                    models.FileField(
                        blank=True, default="", null=True, upload_to="offer_files"
                    ),
                ),
                (
                    "Offer_File_Card_2",
                    models.FileField(
                        blank=True, default="", null=True, upload_to="offer_files"
                    ),
                ),
                (
                    "Offer_File_Card_3",
                    models.FileField(
                        blank=True, default="", null=True, upload_to="offer_files"
                    ),
                ),
                (
                    "Offer_File_Card_4",
                    models.FileField(
                        blank=True, default="", null=True, upload_to="offer_files"
                    ),
                ),
                (
                    "Offer_File_Card_5",
                    models.FileField(
                        blank=True, default="", null=True, upload_to="offer_files"
                    ),
                ),
                (
                    "M_File_Card",
                    models.FileField(
                        blank=True, default="", null=True, upload_to="m_files"
                    ),
                ),
                (
                    "M_File_Card_2",
                    models.FileField(
                        blank=True, default="", null=True, upload_to="m_files"
                    ),
                ),
                (
                    "M_File_Card_3",
                    models.FileField(
                        blank=True, default="", null=True, upload_to="m_files"
                    ),
                ),
                ("Is_Lost", models.BooleanField(blank=True, default=False, null=True)),
                ("Is_Gain", models.BooleanField(blank=True, default=False, null=True)),
                ("Is_late", models.BooleanField(blank=True, default=False, null=True)),
                (
                    "Client_Card",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="AFM.clients",
                    ),
                ),
                (
                    "Revise_Owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="AFM.salesoffercard",
                    ),
                ),
            ],
        ),
    ]
