# Generated by Django 5.0 on 2024-01-21 15:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("AFM", "0040_salesoffercard_revise"),
    ]

    operations = [
        migrations.AddField(
            model_name="salesoffercard_revise",
            name="Person_Deal",
            field=models.CharField(blank=True, max_length=63, null=True),
        ),
        migrations.AlterField(
            model_name="salesoffercard_revise",
            name="Roof_Cost_Card",
            field=models.IntegerField(blank=True, default="0", null=True),
        ),
    ]
