# Generated by Django 5.0 on 2024-01-21 16:41

import AFM.models
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("AFM", "0041_salesoffercard_revise_person_deal_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="salesoffercard",
            name="Profit_Rate_Card",
            field=AFM.models.TwoDecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
        migrations.AddField(
            model_name="salesoffercard",
            name="Unit_Cost_with_Roof_Cost",
            field=AFM.models.TwoDecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
        migrations.AddField(
            model_name="salesoffercard",
            name="Unit_Offer_with_Roof_Cost",
            field=AFM.models.TwoDecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
        migrations.AddField(
            model_name="salesoffercard_revise",
            name="Profit_Rate_Card",
            field=AFM.models.TwoDecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
        migrations.AddField(
            model_name="salesoffercard_revise",
            name="Unit_Cost_with_Roof_Cost",
            field=AFM.models.TwoDecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
        migrations.AddField(
            model_name="salesoffercard_revise",
            name="Unit_Offer_with_Roof_Cost",
            field=AFM.models.TwoDecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
    ]
