# Generated by Django 5.0 on 2024-01-28 20:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("AFM", "0043_salesoffercard_person_deal"),
    ]

    operations = [
        migrations.AddField(
            model_name="salesoffercard",
            name="Person_Related",
            field=models.CharField(blank=True, max_length=63, null=True),
        ),
        migrations.AddField(
            model_name="salesoffercard_revise",
            name="Person_Related",
            field=models.CharField(blank=True, max_length=63, null=True),
        ),
    ]
