# Generated by Django 5.0 on 2024-02-01 20:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("AFM", "0044_salesoffercard_person_related_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="salesoffercard_revise",
            name="Revize_created_at",
            field=models.DateTimeField(
                blank=True, default=django.utils.timezone.now, null=True
            ),
        ),
    ]
