# Generated by Django 5.0 on 2024-02-11 12:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("AFM", "0045_salesoffercard_revise_revize_created_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="Worker",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Worker_Name", models.CharField(max_length=63)),
            ],
        ),
    ]
