# Generated by Django 5.0.2 on 2024-02-15 15:42

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AFM', '0046_worker'),
    ]

    operations = [
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Poll_Time', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('Poll_Project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='AFM.project')),
            ],
        ),
        migrations.CreateModel(
            name='Poll_Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Questin_Type_Number', models.IntegerField(blank=True, null=True)),
                ('Questin_Number', models.IntegerField(blank=True, null=True)),
                ('Question_Poll', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='AFM.poll')),
            ],
        ),
        migrations.CreateModel(
            name='Poll_Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Answer_Text', models.CharField(blank=True, max_length=63, null=True)),
                ('Answer_value', models.BooleanField(blank=True, null=True)),
                ('Answer_Poll', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='AFM.poll_question')),
            ],
        ),
        migrations.CreateModel(
            name='Question_Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Note_Text', models.CharField(blank=True, max_length=255, null=True)),
                ('Note_Question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='AFM.poll_question')),
            ],
        ),
        migrations.CreateModel(
            name='Time_Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Note_Text', models.CharField(blank=True, max_length=2550, null=True)),
                ('Note_Editör', models.CharField(blank=True, max_length=255, null=True)),
                ('Edit_Time', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('Note_Investigator', models.CharField(blank=True, max_length=255, null=True)),
                ('Investigation_Time', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('Note_Poll', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='AFM.poll')),
            ],
        ),
    ]
