# Generated by Django 5.0.2 on 2024-02-28 18:16

import AFM.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AFM', '0049_fail_bill'),
    ]

    operations = [
        migrations.AddField(
            model_name='operation_care',
            name='Operation_Care_Number_Str',
            field=AFM.models.TwoDecimalField(blank=True, decimal_places=2, default='0', max_digits=30, null=True),
        ),
    ]
