# Generated by Django 5.0.2 on 2024-03-01 08:18

import AFM.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AFM', '0051_fail_fail_repair_date_fail_fail_situation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='operation_care',
            name='Operation_Care_Cost',
            field=AFM.models.TwoDecimalField(blank=True, decimal_places=2, default='0', max_digits=30, null=True),
        ),
        migrations.CreateModel(
            name='Inventor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Inventor_Owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='AFM.operation_care')),
            ],
        ),
    ]
