# Generated by Django 5.0.2 on 2024-03-01 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AFM', '0052_operation_care_operation_care_cost_inventor'),
    ]

    operations = [
        migrations.AddField(
            model_name='fail',
            name='Fail_Operation_Care_Copy',
            field=models.CharField(blank=True, max_length=63, null=True),
        ),
    ]
