# Generated by Django 5.0.2 on 2024-03-01 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AFM', '0053_fail_fail_operation_care_copy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fail',
            name='Fail_Situation',
            field=models.CharField(blank=True, choices=[('Belirlendi', 'Belirlendi'), ('Onarımda', 'Onarımda'), ('Onarıldı', 'Onarıldı')], default='Belirlendi', max_length=63, null=True),
        ),
        migrations.AlterField(
            model_name='operation_care',
            name='Operation_Care_AC_Power',
            field=models.IntegerField(blank=True, default='0', null=True),
        ),
        migrations.AlterField(
            model_name='operation_care',
            name='Operation_Care_Capacity',
            field=models.IntegerField(blank=True, default='0', null=True),
        ),
        migrations.AlterField(
            model_name='operation_care',
            name='Operation_Care_Cost',
            field=models.IntegerField(blank=True, default='0', null=True),
        ),
        migrations.AlterField(
            model_name='operation_care',
            name='Operation_Care_DC_Power',
            field=models.IntegerField(blank=True, default='0', null=True),
        ),
        migrations.AlterField(
            model_name='operation_care',
            name='Operation_Care_Inventor_Number',
            field=models.IntegerField(blank=True, default='0', null=True),
        ),
        migrations.AlterField(
            model_name='operation_care',
            name='Operation_Care_Inventor_Power',
            field=models.IntegerField(blank=True, default='0', null=True),
        ),
        migrations.AlterField(
            model_name='operation_care',
            name='Operation_Care_Number_Str',
            field=models.IntegerField(blank=True, default='0', null=True),
        ),
        migrations.AlterField(
            model_name='operation_care',
            name='Operation_Care_Panel_Number_Str',
            field=models.IntegerField(blank=True, default='0', null=True),
        ),
        migrations.AlterField(
            model_name='operation_care',
            name='Operation_Care_Panel_Power',
            field=models.IntegerField(blank=True, default='0', null=True),
        ),
        migrations.AlterField(
            model_name='operation_care',
            name='Operation_Care_VOC',
            field=models.IntegerField(blank=True, default='0', null=True),
        ),
    ]
