# Generated by Django 5.0.2 on 2024-03-02 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AFM', '0054_alter_fail_fail_situation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventor',
            name='Inventor_Direction',
            field=models.CharField(blank=True, max_length=63, null=True),
        ),
        migrations.AddField(
            model_name='inventor',
            name='Inventor_Izolasyon',
            field=models.CharField(blank=True, max_length=63, null=True),
        ),
        migrations.AddField(
            model_name='inventor',
            name='Inventor_Number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inventor',
            name='Inventor_Number_Str',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inventor',
            name='Inventor_Panel_Brand',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='inventor',
            name='Inventor_Panel_Power',
            field=models.IntegerField(blank=True, default='0', null=True),
        ),
        migrations.AddField(
            model_name='inventor',
            name='Inventor_Panel_SY',
            field=models.IntegerField(blank=True, default='0', null=True),
        ),
        migrations.AddField(
            model_name='inventor',
            name='Inventor_VOC',
            field=models.IntegerField(blank=True, default='0', null=True),
        ),
    ]
