# Generated by Django 5.0.2 on 2024-03-02 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AFM', '0055_inventor_inventor_direction_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventor',
            name='Inventor_Izolasyon',
        ),
    ]
