# Generated by Django 5.0.2 on 2024-03-03 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AFM', '0057_string'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='string',
            name='String_Number_Str',
        ),
        migrations.AddField(
            model_name='inventor',
            name='Inventor_AC_Power',
            field=models.IntegerField(blank=True, default='0', null=True),
        ),
        migrations.AddField(
            model_name='inventor',
            name='Inventor_Capacity',
            field=models.IntegerField(blank=True, default='0', null=True),
        ),
        migrations.AddField(
            model_name='inventor',
            name='Inventor_DC_Power',
            field=models.IntegerField(blank=True, default='0', null=True),
        ),
        migrations.AddField(
            model_name='inventor',
            name='Inventor_Izolasion',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='string',
            name='String_AC_Power',
            field=models.IntegerField(blank=True, default='0', null=True),
        ),
        migrations.AddField(
            model_name='string',
            name='String_Capacity',
            field=models.IntegerField(blank=True, default='0', null=True),
        ),
        migrations.AddField(
            model_name='string',
            name='String_DC_Power',
            field=models.IntegerField(blank=True, default='0', null=True),
        ),
        migrations.AddField(
            model_name='string',
            name='String_Izolasion',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
