# Generated by Django 5.0.2 on 2024-03-07 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AFM', '0059_string_string_percent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fail',
            name='Fail_Guaranteed',
            field=models.CharField(blank=True, max_length=63, null=True),
        ),
    ]
