# Generated by Django 5.0.2 on 2024-03-07 22:37

import AFM.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AFM', '0060_alter_fail_fail_guaranteed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fail',
            name='Fail_Guaranteed',
            field=models.CharField(choices=[('Belirlenmedi', 'Belirlenmedi'), ('Evet', 'Evet'), ('Hayır', 'Hayır')], default='Belirlenmedi', max_length=63, null=True),
        ),
        migrations.AlterField(
            model_name='salesoffercard',
            name='Roof_Cost_Card',
            field=AFM.models.TwoDecimalField(blank=True, decimal_places=2, max_digits=30, null=True),
        ),
    ]
