# Generated by Django 5.0.2 on 2024-03-10 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AFM', '0061_alter_fail_fail_guaranteed_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expenses',
            old_name='Amount_TL_Expenses',
            new_name='Amount_USD_Expenses',
        ),
    ]
