# Generated by Django 5.0.2 on 2024-03-10 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AFM', '0062_rename_amount_tl_expenses_expenses_amount_usd_expenses'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobhistory',
            old_name='Amount_TL_JobHistory',
            new_name='Amount_USD_JobHistory',
        ),
    ]
