# Generated by Django 5.0.3 on 2024-03-12 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AFM', '0063_rename_amount_tl_jobhistory_jobhistory_amount_usd_jobhistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clients',
            name='CompanyName_Clients_New',
        ),
    ]
