# Generated by Django 5.0.3 on 2024-03-16 15:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AFM', '0065_clients_companyname_clients_new'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expenses',
            name='ProjectCode_Expenses',
        ),
        migrations.RemoveField(
            model_name='expenses',
            name='ProjectName_Expenses',
        ),
        migrations.RemoveField(
            model_name='expenses',
            name='ProjectName_Expenses_Copy',
        ),
        migrations.RemoveField(
            model_name='incomes',
            name='ProjectName_Incomes',
        ),
        migrations.RemoveField(
            model_name='incomes',
            name='ProjectName_Incomes_Copy',
        ),
        migrations.RemoveField(
            model_name='jobhistory',
            name='ProjectName_JobHistory',
        ),
        migrations.RemoveField(
            model_name='jobhistory',
            name='ProjectName_JobHistory_Copy',
        ),
        migrations.RemoveField(
            model_name='project',
            name='CompanyName',
        ),
        migrations.AddField(
            model_name='expenses',
            name='Project_Expenses',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='AFM.project'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='incomes',
            name='Project_Incomes',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='AFM.project'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobhistory',
            name='Project_JobHistory',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='AFM.project'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='Company_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='AFM.clients'),
        ),
    ]
