# Generated by Django 5.0.3 on 2024-03-16 15:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AFM', '0066_remove_expenses_projectcode_expenses_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProjectNames',
        ),
        migrations.AlterField(
            model_name='incomes',
            name='CompanyName_Pay_Incomes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='AFM.clients'),
        ),
    ]
