# Generated by Django 5.0.3 on 2024-03-16 20:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AFM', '0067_delete_projectnames_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expenses',
            name='CompanyName_Expenses',
        ),
        migrations.RemoveField(
            model_name='jobhistory',
            name='CompanyName_JobHistory',
        ),
        migrations.AlterField(
            model_name='expenses',
            name='CompanyName_Paying_Expenses',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='AFM.supplier'),
        ),
        migrations.AlterField(
            model_name='jobhistory',
            name='CompanyName_Job_JobHistory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='AFM.supplier'),
        ),
    ]
