# Generated by Django 5.0.3 on 2024-03-16 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AFM', '0068_remove_expenses_companyname_expenses_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clients',
            name='CompanyName_Clients_New',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='CompanyName_Supplier_New',
        ),
        migrations.AlterField(
            model_name='clients',
            name='CompanyName_Clients',
            field=models.CharField(default=123, max_length=63, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='supplier',
            name='CompanyName_Supplier',
            field=models.CharField(default=1, max_length=63, unique=True),
            preserve_default=False,
        ),
    ]
