# Generated by Django 5.0.3 on 2024-03-17 02:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AFM', '0069_remove_clients_companyname_clients_new_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesoffercard',
            name='Client_Card_Copy',
        ),
        migrations.RemoveField(
            model_name='salesoffercard_revise',
            name='Client_Card_Copy',
        ),
    ]
