# Generated by Django 5.0.3 on 2024-03-18 07:09

import AFM.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AFM', '0070_remove_salesoffercard_client_card_copy_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenses',
            name='Amount_Expenses',
            field=AFM.models.TwoDecimalField(blank=True, decimal_places=2, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='expenses',
            name='Amount_USD_Expenses',
            field=AFM.models.TwoDecimalField(blank=True, decimal_places=2, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='Company_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clients', to='AFM.clients'),
        ),
    ]
