# Generated by Django 5.0.3 on 2024-03-18 07:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AFM', '0071_alter_expenses_amount_expenses_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='Company_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='AFM.clients'),
        ),
    ]
