# Generated by Django 5.0.3 on 2024-03-18 15:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AFM', '0072_alter_project_company_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenses',
            name='CompanyName_Paying_Expenses',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplier_expenses', to='AFM.supplier'),
        ),
        migrations.AlterField(
            model_name='expenses',
            name='Project_Expenses',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_expenses', to='AFM.project'),
        ),
        migrations.AlterField(
            model_name='incomes',
            name='CompanyName_Pay_Incomes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_jobhistories', to='AFM.clients'),
        ),
        migrations.AlterField(
            model_name='incomes',
            name='Project_Incomes',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_incomes', to='AFM.project'),
        ),
        migrations.AlterField(
            model_name='jobhistory',
            name='CompanyName_Job_JobHistory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplier_jobhistories', to='AFM.supplier'),
        ),
        migrations.AlterField(
            model_name='jobhistory',
            name='Project_JobHistory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_jobhistories', to='AFM.project'),
        ),
        migrations.AlterField(
            model_name='salesoffercard',
            name='Client_Card',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client_salesoffers', to='AFM.clients'),
        ),
        migrations.AlterField(
            model_name='salesoffercard_revise',
            name='Client_Card',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client_salesoffer_revises', to='AFM.clients'),
        ),
        migrations.AlterField(
            model_name='salesoffercard_revise',
            name='Revise_Owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='salesoffer_revises', to='AFM.salesoffercard'),
        ),
    ]
