# Generated by Django 5.0.3 on 2024-03-18 15:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AFM', '0073_alter_expenses_companyname_paying_expenses_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incomes',
            name='CompanyName_Pay_Incomes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_incomes', to='AFM.clients'),
        ),
    ]
