# Generated by Django 5.0.3 on 2024-03-24 12:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AFM', '0074_alter_incomes_companyname_pay_incomes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesoffercard',
            name='Client_Card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_salesoffers', to='AFM.clients'),
        ),
    ]
