# Generated by Django 5.0.3 on 2024-03-27 18:30

import AFM.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AFM', '0075_alter_salesoffercard_client_card'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fail',
            name='Fail_Operation_Care',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operation_fails', to='AFM.operation_care'),
        ),
        migrations.AlterField(
            model_name='fail_bill',
            name='Fail_Bill_Owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fail_bills', to='AFM.fail'),
        ),
        migrations.AlterField(
            model_name='inventor',
            name='Inventor_Owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operation_inventors', to='AFM.operation_care'),
        ),
        migrations.AlterField(
            model_name='inventor',
            name='Inventor_VOC',
            field=AFM.models.TwoDecimalField(blank=True, decimal_places=2, default='0', max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='operation_care',
            name='Operation_Care_Company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_operation_care', to='AFM.clients'),
        ),
        migrations.AlterField(
            model_name='operation_care',
            name='Operation_Care_VOC',
            field=AFM.models.TwoDecimalField(blank=True, decimal_places=2, default='0', max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='string',
            name='String_Owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventor_strings', to='AFM.inventor'),
        ),
        migrations.AlterField(
            model_name='string',
            name='String_VOC',
            field=AFM.models.TwoDecimalField(blank=True, decimal_places=2, default='0', max_digits=30, null=True),
        ),
    ]
