# Generated by Django 5.0.3 on 2024-03-27 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AFM', '0076_alter_fail_fail_operation_care_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fail',
            name='Fail_Operation_Care_Copy',
        ),
    ]
