# Generated by Django 5.0.3 on 2024-03-30 22:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AFM', '0077_remove_fail_fail_operation_care_copy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fail_bill',
            name='Fail_Bill_Owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fail_bills', to='AFM.fail'),
        ),
    ]
