# Generated by Django 5.0.3 on 2024-03-31 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AFM', '0078_alter_fail_bill_fail_bill_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='fail',
            name='Fail_Bill_Central_Name',
            field=models.CharField(blank=True, max_length=63, null=True),
        ),
        migrations.AddField(
            model_name='fail',
            name='Fail_Bill_Date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fail',
            name='Fail_Bill_Detail',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='fail',
            name='Fail_Bill_File',
            field=models.FileField(blank=True, default='', null=True, upload_to='fail_bills'),
        ),
        migrations.AddField(
            model_name='fail',
            name='Fail_Bill_Process',
            field=models.CharField(blank=True, max_length=63, null=True),
        ),
        migrations.DeleteModel(
            name='Fail_Bill',
        ),
    ]
