# Generated by Django 5.0.3 on 2024-04-03 12:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AFM', '0079_fail_fail_bill_central_name_fail_fail_bill_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poll_question',
            name='Question_Poll',
        ),
        migrations.RemoveField(
            model_name='question_note',
            name='Note_Question',
        ),
        migrations.RemoveField(
            model_name='time_note',
            name='Note_Poll',
        ),
        migrations.RemoveField(
            model_name='poll',
            name='Poll_Time',
        ),
        migrations.AddField(
            model_name='poll',
            name='Note_1_1',
            field=models.CharField(blank=True, max_length=127, null=True),
        ),
        migrations.AddField(
            model_name='poll',
            name='Note_1_2',
            field=models.CharField(blank=True, max_length=127, null=True),
        ),
        migrations.AddField(
            model_name='poll',
            name='Note_1_3',
            field=models.CharField(blank=True, max_length=127, null=True),
        ),
        migrations.AddField(
            model_name='poll',
            name='Note_1_4',
            field=models.CharField(blank=True, max_length=127, null=True),
        ),
        migrations.AddField(
            model_name='poll',
            name='Note_1_5',
            field=models.CharField(blank=True, max_length=127, null=True),
        ),
        migrations.AddField(
            model_name='poll',
            name='Note_1_6',
            field=models.CharField(blank=True, max_length=127, null=True),
        ),
        migrations.AddField(
            model_name='poll',
            name='Note_2_1',
            field=models.CharField(blank=True, max_length=127, null=True),
        ),
        migrations.AddField(
            model_name='poll',
            name='Note_2_2',
            field=models.CharField(blank=True, max_length=127, null=True),
        ),
        migrations.AddField(
            model_name='poll',
            name='Note_2_3',
            field=models.CharField(blank=True, max_length=127, null=True),
        ),
        migrations.AddField(
            model_name='poll',
            name='Note_2_4',
            field=models.CharField(blank=True, max_length=127, null=True),
        ),
        migrations.AddField(
            model_name='poll',
            name='Note_2_5',
            field=models.CharField(blank=True, max_length=127, null=True),
        ),
        migrations.AddField(
            model_name='poll',
            name='Note_2_6',
            field=models.CharField(blank=True, max_length=127, null=True),
        ),
        migrations.AddField(
            model_name='poll',
            name='Note_2_7',
            field=models.CharField(blank=True, max_length=127, null=True),
        ),
        migrations.AddField(
            model_name='poll',
            name='Note_3_1',
            field=models.CharField(blank=True, max_length=127, null=True),
        ),
        migrations.AddField(
            model_name='poll',
            name='Note_3_2',
            field=models.CharField(blank=True, max_length=127, null=True),
        ),
        migrations.AddField(
            model_name='poll',
            name='Note_3_3',
            field=models.CharField(blank=True, max_length=127, null=True),
        ),
        migrations.AddField(
            model_name='poll',
            name='Note_3_4',
            field=models.CharField(blank=True, max_length=127, null=True),
        ),
        migrations.AddField(
            model_name='poll',
            name='Note_4_1',
            field=models.CharField(blank=True, max_length=127, null=True),
        ),
        migrations.AddField(
            model_name='poll',
            name='Note_4_2',
            field=models.CharField(blank=True, max_length=127, null=True),
        ),
        migrations.AddField(
            model_name='poll',
            name='Note_4_3',
            field=models.CharField(blank=True, max_length=127, null=True),
        ),
        migrations.AddField(
            model_name='poll',
            name='Note_4_4',
            field=models.CharField(blank=True, max_length=127, null=True),
        ),
        migrations.AddField(
            model_name='poll',
            name='Note_4_5',
            field=models.CharField(blank=True, max_length=127, null=True),
        ),
        migrations.AddField(
            model_name='poll',
            name='Note_5_1',
            field=models.CharField(blank=True, max_length=127, null=True),
        ),
        migrations.AddField(
            model_name='poll',
            name='Note_5_2',
            field=models.CharField(blank=True, max_length=127, null=True),
        ),
        migrations.AddField(
            model_name='poll',
            name='Note_5_3',
            field=models.CharField(blank=True, max_length=127, null=True),
        ),
        migrations.AddField(
            model_name='poll',
            name='Note_5_4',
            field=models.CharField(blank=True, max_length=127, null=True),
        ),
        migrations.AddField(
            model_name='poll',
            name='Note_6_1',
            field=models.CharField(blank=True, max_length=127, null=True),
        ),
        migrations.AddField(
            model_name='poll',
            name='Note_6_2',
            field=models.CharField(blank=True, max_length=127, null=True),
        ),
        migrations.AddField(
            model_name='poll',
            name='Note_6_3',
            field=models.CharField(blank=True, max_length=127, null=True),
        ),
        migrations.AddField(
            model_name='poll',
            name='Note_6_4',
            field=models.CharField(blank=True, max_length=127, null=True),
        ),
        migrations.AddField(
            model_name='poll',
            name='Note_6_5',
            field=models.CharField(blank=True, max_length=127, null=True),
        ),
        migrations.AddField(
            model_name='poll',
            name='Note_6_6',
            field=models.CharField(blank=True, max_length=127, null=True),
        ),
        migrations.AddField(
            model_name='poll',
            name='Note_7_1',
            field=models.CharField(blank=True, max_length=127, null=True),
        ),
        migrations.AddField(
            model_name='poll',
            name='Note_7_2',
            field=models.CharField(blank=True, max_length=127, null=True),
        ),
        migrations.AddField(
            model_name='poll',
            name='Note_7_3',
            field=models.CharField(blank=True, max_length=127, null=True),
        ),
        migrations.AddField(
            model_name='poll',
            name='Note_7_4',
            field=models.CharField(blank=True, max_length=127, null=True),
        ),
        migrations.AddField(
            model_name='poll',
            name='Note_7_5',
            field=models.CharField(blank=True, max_length=127, null=True),
        ),
        migrations.AddField(
            model_name='poll',
            name='Note_7_6',
            field=models.CharField(blank=True, max_length=127, null=True),
        ),
        migrations.AddField(
            model_name='poll',
            name='Note_7_7',
            field=models.CharField(blank=True, max_length=127, null=True),
        ),
        migrations.AddField(
            model_name='poll',
            name='Note_8_1',
            field=models.CharField(blank=True, max_length=127, null=True),
        ),
        migrations.AddField(
            model_name='poll',
            name='Note_8_2',
            field=models.CharField(blank=True, max_length=127, null=True),
        ),
        migrations.AddField(
            model_name='poll',
            name='Note_8_3',
            field=models.CharField(blank=True, max_length=127, null=True),
        ),
        migrations.AddField(
            model_name='poll',
            name='Note_8_4',
            field=models.CharField(blank=True, max_length=127, null=True),
        ),
        migrations.AddField(
            model_name='poll',
            name='Note_8_5',
            field=models.CharField(blank=True, max_length=127, null=True),
        ),
        migrations.AddField(
            model_name='poll',
            name='Note_8_6',
            field=models.CharField(blank=True, max_length=127, null=True),
        ),
        migrations.AddField(
            model_name='poll',
            name='Note_8_7',
            field=models.CharField(blank=True, max_length=127, null=True),
        ),
        migrations.AddField(
            model_name='poll',
            name='Note_8_8',
            field=models.CharField(blank=True, max_length=127, null=True),
        ),
        migrations.AddField(
            model_name='poll',
            name='Note_9_1',
            field=models.CharField(blank=True, max_length=127, null=True),
        ),
        migrations.AddField(
            model_name='poll',
            name='Note_9_2',
            field=models.CharField(blank=True, max_length=127, null=True),
        ),
        migrations.AddField(
            model_name='poll',
            name='Note_9_3',
            field=models.CharField(blank=True, max_length=127, null=True),
        ),
        migrations.AddField(
            model_name='poll',
            name='Note_9_4',
            field=models.CharField(blank=True, max_length=127, null=True),
        ),
        migrations.AddField(
            model_name='poll',
            name='Note_9_5',
            field=models.CharField(blank=True, max_length=127, null=True),
        ),
        migrations.AddField(
            model_name='poll',
            name='Poll_Date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Poll_Cloumn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cloumn_Time', models.DateField(blank=True, null=True)),
                ('Cloumn_Note_Text', models.TextField(blank=True, max_length=1000, null=True)),
                ('Cloumn_Organizer', models.CharField(blank=True, max_length=100, null=True)),
                ('Cloumn_Organize_Date', models.DateField(blank=True, null=True)),
                ('Cloumn_Looker', models.CharField(blank=True, max_length=100, null=True)),
                ('Cloumn_Looker_Date', models.DateField(blank=True, null=True)),
                ('answer_1_1', models.BooleanField(default=False)),
                ('answer_1_2', models.BooleanField(default=False)),
                ('answer_1_3', models.BooleanField(default=False)),
                ('answer_1_4', models.BooleanField(default=False)),
                ('answer_1_5', models.BooleanField(default=False)),
                ('answer_1_6', models.BooleanField(default=False)),
                ('answer_2_1', models.BooleanField(default=False)),
                ('answer_2_2', models.BooleanField(default=False)),
                ('answer_2_3', models.BooleanField(default=False)),
                ('answer_2_4', models.BooleanField(default=False)),
                ('answer_2_5', models.BooleanField(default=False)),
                ('answer_2_6', models.BooleanField(default=False)),
                ('answer_2_7', models.BooleanField(default=False)),
                ('answer_3_1', models.BooleanField(default=False)),
                ('answer_3_2', models.BooleanField(default=False)),
                ('answer_3_3', models.BooleanField(default=False)),
                ('answer_3_4', models.BooleanField(default=False)),
                ('answer_4_1', models.BooleanField(default=False)),
                ('answer_4_2', models.BooleanField(default=False)),
                ('answer_4_3', models.BooleanField(default=False)),
                ('answer_4_4', models.BooleanField(default=False)),
                ('answer_4_5', models.BooleanField(default=False)),
                ('answer_5_1', models.BooleanField(default=False)),
                ('answer_5_2', models.BooleanField(default=False)),
                ('answer_5_3', models.BooleanField(default=False)),
                ('answer_5_4', models.BooleanField(default=False)),
                ('answer_6_1', models.BooleanField(default=False)),
                ('answer_6_2', models.BooleanField(default=False)),
                ('answer_6_3', models.BooleanField(default=False)),
                ('answer_6_4', models.BooleanField(default=False)),
                ('answer_6_5', models.BooleanField(default=False)),
                ('answer_6_6', models.BooleanField(default=False)),
                ('answer_7_1', models.BooleanField(default=False)),
                ('answer_7_2', models.BooleanField(default=False)),
                ('answer_7_3', models.BooleanField(default=False)),
                ('answer_7_4', models.BooleanField(default=False)),
                ('answer_7_5', models.BooleanField(default=False)),
                ('answer_7_6', models.BooleanField(default=False)),
                ('answer_7_7', models.BooleanField(default=False)),
                ('answer_8_1', models.BooleanField(default=False)),
                ('answer_8_2', models.BooleanField(default=False)),
                ('answer_8_3', models.BooleanField(default=False)),
                ('answer_8_4', models.BooleanField(default=False)),
                ('answer_8_5', models.BooleanField(default=False)),
                ('answer_8_6', models.BooleanField(default=False)),
                ('answer_8_7', models.BooleanField(default=False)),
                ('answer_8_8', models.BooleanField(default=False)),
                ('answer_9_1', models.BooleanField(default=False)),
                ('answer_9_2', models.BooleanField(default=False)),
                ('answer_9_3', models.BooleanField(default=False)),
                ('answer_9_4', models.BooleanField(default=False)),
                ('answer_9_5', models.BooleanField(default=False)),
                ('Cloumn_Poll', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='AFM.poll')),
            ],
        ),
        migrations.DeleteModel(
            name='Poll_Answer',
        ),
        migrations.DeleteModel(
            name='Poll_Question',
        ),
        migrations.DeleteModel(
            name='Question_Note',
        ),
        migrations.DeleteModel(
            name='Time_Note',
        ),
    ]
