# Generated by Django 5.0.3 on 2024-04-14 21:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AFM', '0081_poll_cloumn_looker_poll_cloumn_looker_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='Poll_Date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='poll',
            name='Poll_Operation_Care',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='op_poll', to='AFM.operation_care'),
        ),
    ]
