# Generated by Django 5.0.3 on 2024-04-29 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AFM', '0082_alter_poll_poll_date_alter_poll_poll_operation_care'),
    ]

    operations = [
        migrations.AddField(
            model_name='string',
            name='String_Direction',
            field=models.CharField(blank=True, max_length=63, null=True),
        ),
    ]
