# Generated by Django 5.0.3 on 2024-05-01 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AFM', '0083_string_string_direction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fail',
            name='Fail_Guaranteed',
            field=models.CharField(choices=[('Belirsiz', 'Belirsiz'), ('Evet', 'Evet'), ('Hayır', 'Hayır')], default='Belirlenmedi', max_length=63, null=True),
        ),
    ]
