# Generated by Django 5.0.3 on 2024-05-05 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AFM', '0084_alter_fail_fail_guaranteed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesoffercard',
            name='Comment_Date_Card',
        ),
        migrations.RemoveField(
            model_name='salesoffercard',
            name='Offer_Comment_Card',
        ),
        migrations.AddField(
            model_name='salesoffercard',
            name='Comment_Card_1',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='salesoffercard',
            name='Comment_Card_2',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='salesoffercard',
            name='Comment_Card_3',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='salesoffercard',
            name='Comment_Card_4',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='salesoffercard',
            name='Comment_Card_5',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='salesoffercard',
            name='Comment_Card_6',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='salesoffercard',
            name='Comment_Card_7',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='salesoffercard',
            name='Comment_Date_Card_1',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='salesoffercard',
            name='Comment_Date_Card_2',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='salesoffercard',
            name='Comment_Date_Card_3',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='salesoffercard',
            name='Comment_Date_Card_4',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='salesoffercard',
            name='Comment_Date_Card_5',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='salesoffercard',
            name='Comment_Date_Card_6',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='salesoffercard',
            name='Comment_Date_Card_7',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='salesoffercard',
            name='Comment_Person_Card_1',
            field=models.CharField(blank=True, max_length=63, null=True),
        ),
        migrations.AddField(
            model_name='salesoffercard',
            name='Comment_Person_Card_2',
            field=models.CharField(blank=True, max_length=63, null=True),
        ),
        migrations.AddField(
            model_name='salesoffercard',
            name='Comment_Person_Card_3',
            field=models.CharField(blank=True, max_length=63, null=True),
        ),
        migrations.AddField(
            model_name='salesoffercard',
            name='Comment_Person_Card_4',
            field=models.CharField(blank=True, max_length=63, null=True),
        ),
        migrations.AddField(
            model_name='salesoffercard',
            name='Comment_Person_Card_5',
            field=models.CharField(blank=True, max_length=63, null=True),
        ),
        migrations.AddField(
            model_name='salesoffercard',
            name='Comment_Person_Card_6',
            field=models.CharField(blank=True, max_length=63, null=True),
        ),
        migrations.AddField(
            model_name='salesoffercard',
            name='Comment_Person_Card_7',
            field=models.CharField(blank=True, max_length=63, null=True),
        ),
        migrations.AddField(
            model_name='salesoffercard',
            name='Comment_Telno_Card_1',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='salesoffercard',
            name='Comment_Telno_Card_2',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='salesoffercard',
            name='Comment_Telno_Card_3',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='salesoffercard',
            name='Comment_Telno_Card_4',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='salesoffercard',
            name='Comment_Telno_Card_5',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='salesoffercard',
            name='Comment_Telno_Card_6',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='salesoffercard',
            name='Comment_Telno_Card_7',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
