# Generated by Django 5.0.3 on 2024-05-05 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AFM', '0086_remove_salesoffercard_revise_comment_date_card_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='operation_care',
            name='Operation_Care_Switchgear_Material',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
