# Generated by Django 5.0.3 on 2024-05-07 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AFM', '0088_string_string_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='answer_1_1',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='poll',
            name='answer_1_2',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='poll',
            name='answer_1_3',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='poll',
            name='answer_1_4',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='poll',
            name='answer_1_5',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='poll',
            name='answer_1_6',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='poll',
            name='answer_2_1',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='poll',
            name='answer_2_2',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='poll',
            name='answer_2_3',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='poll',
            name='answer_2_4',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='poll',
            name='answer_2_5',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='poll',
            name='answer_2_6',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='poll',
            name='answer_2_7',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='poll',
            name='answer_3_1',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='poll',
            name='answer_3_2',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='poll',
            name='answer_3_3',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='poll',
            name='answer_3_4',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='poll',
            name='answer_4_1',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='poll',
            name='answer_4_2',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='poll',
            name='answer_4_3',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='poll',
            name='answer_4_4',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='poll',
            name='answer_4_5',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='poll',
            name='answer_5_1',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='poll',
            name='answer_5_2',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='poll',
            name='answer_5_3',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='poll',
            name='answer_5_4',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='poll',
            name='answer_6_1',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='poll',
            name='answer_6_2',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='poll',
            name='answer_6_3',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='poll',
            name='answer_6_4',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='poll',
            name='answer_6_5',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='poll',
            name='answer_6_6',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='poll',
            name='answer_7_1',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='poll',
            name='answer_7_2',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='poll',
            name='answer_7_3',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='poll',
            name='answer_7_4',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='poll',
            name='answer_7_5',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='poll',
            name='answer_7_6',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='poll',
            name='answer_7_7',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='poll',
            name='answer_8_1',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='poll',
            name='answer_8_2',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='poll',
            name='answer_8_3',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='poll',
            name='answer_8_4',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='poll',
            name='answer_8_5',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='poll',
            name='answer_8_6',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='poll',
            name='answer_8_7',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='poll',
            name='answer_8_8',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='poll',
            name='answer_9_1',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='poll',
            name='answer_9_2',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='poll',
            name='answer_9_3',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='poll',
            name='answer_9_4',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='poll',
            name='answer_9_5',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
