# Generated by Django 5.0.3 on 2024-05-08 15:49

import AFM.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AFM', '0089_alter_poll_answer_1_1_alter_poll_answer_1_2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventor',
            name='Inventor_AC_Power',
            field=AFM.models.TwoDecimalField(blank=True, decimal_places=2, default='0', max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='inventor',
            name='Inventor_DC_Power',
            field=AFM.models.TwoDecimalField(blank=True, decimal_places=2, default='0', max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='operation_care',
            name='Operation_Care_AC_Power',
            field=AFM.models.TwoDecimalField(blank=True, decimal_places=2, default='0', max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='operation_care',
            name='Operation_Care_DC_Power',
            field=AFM.models.TwoDecimalField(blank=True, decimal_places=2, default='0', max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='AC_Power',
            field=AFM.models.TwoDecimalField(blank=True, decimal_places=2, default=0, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='DC_Power',
            field=AFM.models.TwoDecimalField(blank=True, decimal_places=2, default=0, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='salesoffercard',
            name='AC_Power_Card',
            field=AFM.models.TwoDecimalField(blank=True, decimal_places=2, default='0', max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='salesoffercard',
            name='DC_Power_Card',
            field=AFM.models.TwoDecimalField(blank=True, decimal_places=2, default='0', max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='salesoffercard_revise',
            name='AC_Power_Card',
            field=AFM.models.TwoDecimalField(blank=True, decimal_places=2, default='0', max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='salesoffercard_revise',
            name='DC_Power_Card',
            field=AFM.models.TwoDecimalField(blank=True, decimal_places=2, default='0', max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='string',
            name='String_AC_Power',
            field=AFM.models.TwoDecimalField(blank=True, decimal_places=2, default='0', max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='string',
            name='String_DC_Power',
            field=AFM.models.TwoDecimalField(blank=True, decimal_places=2, default='0', max_digits=30, null=True),
        ),
    ]
