# Generated by Django 5.0.3 on 2024-05-22 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AFM', '0091_operation_care_operation_care_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='operation_care',
            name='Operation_Care_endContract_Date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
