# Generated by Django 5.0.3 on 2024-05-31 19:21

import AFM.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AFM', '0092_operation_care_operation_care_endcontract_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventor',
            name='Inventor_Minus',
            field=AFM.models.FourDecimalField(blank=True, decimal_places=4, default='0', max_digits=30, null=True),
        ),
        migrations.AddField(
            model_name='inventor',
            name='Inventor_Pluse',
            field=AFM.models.FourDecimalField(blank=True, decimal_places=4, default='0', max_digits=30, null=True),
        ),
        migrations.AddField(
            model_name='string',
            name='String_Minus',
            field=AFM.models.FourDecimalField(blank=True, decimal_places=4, default='0', max_digits=30, null=True),
        ),
        migrations.AddField(
            model_name='string',
            name='String_Pluse',
            field=AFM.models.FourDecimalField(blank=True, decimal_places=4, default='0', max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='inventor',
            name='Inventor_AC_Power',
            field=AFM.models.FourDecimalField(blank=True, decimal_places=4, default='0', max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='inventor',
            name='Inventor_DC_Power',
            field=AFM.models.FourDecimalField(blank=True, decimal_places=4, default='0', max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='operation_care',
            name='Operation_Care_AC_Power',
            field=AFM.models.FourDecimalField(blank=True, decimal_places=4, default='0', max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='operation_care',
            name='Operation_Care_DC_Power',
            field=AFM.models.FourDecimalField(blank=True, decimal_places=4, default='0', max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='string',
            name='String_AC_Power',
            field=AFM.models.FourDecimalField(blank=True, decimal_places=4, default='0', max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='string',
            name='String_DC_Power',
            field=AFM.models.FourDecimalField(blank=True, decimal_places=4, default='0', max_digits=30, null=True),
        ),
    ]
