# Generated by Django 5.0.3 on 2024-05-31 19:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AFM', '0093_inventor_inventor_minus_inventor_inventor_pluse_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PowerPlant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PowerPlantName', models.CharField(max_length=63)),
            ],
        ),
        migrations.AlterField(
            model_name='operation_care',
            name='Operation_Care_Company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_operation_care', to='AFM.powerplant'),
        ),
    ]
