# Generated by Django 5.0.3 on 2024-07-07 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AFM', '0094_powerplant_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.CharField(max_length=255, verbose_name='Note')),
                ('date', models.DateField(verbose_name='Date')),
                ('start_clock', models.TimeField(verbose_name='Start Time')),
                ('finish_clock', models.TimeField(verbose_name='Finish Time')),
            ],
            options={
                'verbose_name': 'Not',
                'verbose_name_plural': 'Notlar',
                'ordering': ['date', 'start_clock'],
                'indexes': [models.Index(fields=['date'], name='AFM_note_date_216c87_idx')],
            },
        ),
    ]
